follow up comments
Signed-off-by: jooho lee <jlee@redhat.com>

diff --git a/config/runtimes/kserve-huggingfaceserver-multinode.yaml b/config/runtimes/kserve-huggingfaceserver-multinode.yaml
--- a/config/runtimes/kserve-huggingfaceserver-multinode.yaml
+++ b/config/runtimes/kserve-huggingfaceserver-multinode.yaml
@@ -94,7 +94,11 @@ spec:
             - -c
             - |
               # Check if the registered ray nodes count is the same as PIPELINE_PARALLEL_SIZE
-              [[ $(ray status | grep -c node_) -eq ${PIPELINE_PARALLEL_SIZE} ]] &
+              if [[ $(ray status | grep -c node_) -eq ${PIPELINE_PARALLEL_SIZE} ]]; then
+                exit 0
+              else
+                exit 1
+              fi &
               p1=$!
 
               # Check if huggingface server health
@@ -116,8 +120,21 @@ spec:
               p3=$!
 
               # Wait for all processes to complete
-              wait $p1 $p2 $p3
-              wait $p1 && wait $p2 && wait $p3
+              wait $p1
+              status1=$?
+              wait $p2
+              status2=$?
+              wait $p3
+              status3=$?
+
+              # Check all return codes
+              if [[ $status1 -ne 0 || $status2 -ne 0 || $status3 -ne 0 ]]; then
+                  echo "One or more processes failed."
+                  exit 1
+              else
+                  echo "All processes succeeded."
+                  exit 0
+              fi
       startupProbe:
         failureThreshold: 40
         periodSeconds: 30
@@ -193,7 +210,11 @@ spec:
               - bash
               - -c
               - |
-                [[ $(ray status | grep -c node_) -eq ${PIPELINE_PARALLEL_SIZE} ]]
+                if [[ $(ray status | grep -c node_) -eq ${PIPELINE_PARALLEL_SIZE} ]]; then
+                  exit 0
+                else
+                  exit 1
+                fi 
         startupProbe:
           failureThreshold: 12
           periodSeconds: 5
